### PR TITLE
Remove send_transactional_email from core client

### PR DESCRIPTION
**Pull request by sophiemachin**

### CODE REVIEW

**Comment by this-andy** [comment]
https://this.tpondemand.com/entity/4816

**Review by this-andy — COMMENTED** [review]
Does there need to be a corresponding change to yaml file?

**Comment by sophiemachin** [comment]
> Does there need to be a corresponding change to yaml file?

This repo doesn't have a yaml file because it never gets deployed. It only gets installed into other repos via `pip install`

**Comment by sophiemachin** [comment]
@this-andy I think this will need removing from the yaml file in core. I'm be doing that next.

**Pull request merged**
